name: complex-workflow

on: push

jobs:
    job1:
        name: Job 1
        runs-on: ubuntu-latest
        steps:
            - run: date
    job2:
        name: Job 2
        runs-on: windows-latest
        steps:
            - run: date
    job3:
        name: Job 3
        runs-on: macos-latest
        steps:
            - run: date
    job4:
        name: Job 4
        runs-on: macos-14
        steps:
            - run: date
        needs: [job1, job2, job3]